package:
  name: glyles
  version: 0.5.6

source:
  git_url: https://github.com/kalininalab/GlyLES
  git_tag: alper_dev
  path: ./

build:
  script: pip install .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - biopython