package:
  name: glyles
  version: 0.5

source:
  git_url: https://github.com/kalininalab/GlyLES
  git_tag: alper_dev

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: