package:
  name: glyles
  version: 0.5.5

source:
  git_url: https://github.com/kalininalab/GlyLES
  git_tag: alper_dev
  path: ..

build:
  script: pip install .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - biopython