package:
  name: glyles
  version: 0.5.3

source:
  git_url: https://github.com/kalininalab/GlyLES
  git_tag: alper_dev
  path: ..

build:
  script: pip install .

requirements:
  build:
    - python >=3.7,<3.11
    - setuptools
    - attrs=22.1.0
    - brotlipy=0.7.0
    - ca-certificates=2022.10.11
    - cachecontrol=0.12.11
    - cachy=0.3.0
    - certifi=2022.9.24
    - cffi=1.15.1
    - cleo=0.8.1
    - clikit=0.6.2
    - crashtest=0.3.1
    - cryptography=38.0.1
    - distlib=0.3.2
    - filelock=3.6.0
    - html5lib=1.1
    - idna=3.4
    - importlib_metadata=1.7.0
    - keyring=22.3.0
    - lockfile=0.12.2
    - msgpack-python=1.0.3
    - openssl=1.1.1s
    - pastel=0.2.1
    - pip=22.2.2
    - pkginfo=1.8.3
    - platformdirs=2.5.2
    - poetry=1.1.7
    - poetry-core=1.0.3
    - pycparser=2.21
    - pylev=1.3.0
    - pyopenssl=22.0.0
    - pysocks=1.7.1
    - python=3.7.15
    - pywin32-ctypes=0.2.0
    - requests=2.28.1
    - requests-toolbelt=0.9.1
    - setuptools=65.5.0
    - shellingham=1.5.0
    - six=1.16.0
    - sqlite=3.40.0
    - tomlkit=0.11.1
    - urllib3=1.26.12
    - vc=14.2
    - virtualenv=20.16.2
    - vs2015_runtime=14.27.29016
    - webencodings=0.5.1
    - wheel=0.37.1
    - win_inet_pton=1.1.0
    - wincertstore=0.2

  run:
    - python
    - setuptools
    - attrs=22.1.0
    - brotlipy=0.7.0
    - ca-certificates=2022.10.11
    - cachecontrol=0.12.11
    - cachy=0.3.0
    - certifi=2022.9.24
    - cffi=1.15.1
    - cleo=0.8.1
    - clikit=0.6.2
    - crashtest=0.3.1
    - cryptography=38.0.1
    - distlib=0.3.2
    - filelock=3.6.0
    - html5lib=1.1
    - idna=3.4
    - importlib_metadata=1.7.0
    - keyring=22.3.0
    - lockfile=0.12.2
    - msgpack-python=1.0.3
    - openssl=1.1.1s
    - pastel=0.2.1
    - pip=22.2.2
    - pkginfo=1.8.3
    - platformdirs=2.5.2
    - poetry=1.1.7
    - poetry-core=1.0.3
    - pycparser=2.21
    - pylev=1.3.0
    - pyopenssl=22.0.0
    - pysocks=1.7.1
    - python=3.7.15
    - pywin32-ctypes=0.2.0
    - requests=2.28.1
    - requests-toolbelt=0.9.1
    - setuptools=65.5.0
    - shellingham=1.5.0
    - six=1.16.0
    - sqlite=3.40.0
    - tomlkit=0.11.1
    - urllib3=1.26.12
    - vc=14.2
    - virtualenv=20.16.2
    - vs2015_runtime=14.27.29016
    - webencodings=0.5.1
    - wheel=0.37.1
    - win_inet_pton=1.1.0
    - wincertstore=0.2