package:
  name: glyles
  version: 1.0

source:
  git_rev: https://github.com/kalininalab/GlyLES
  git_url: https://github.com/kalininalab/GlyLES

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: